### ISSUE TITLE
Example server does not set cert lookup callback resulting in a crash

### ISSUE THREAD

**Issue by scguoi** [litespeedtech/lsquic#90] opened 2019-12-05 09:58 UTC

**Comment by scguoi** [comment] 2019-12-05 10:00
./http_server -s 127.0.0.1:8443
17:56:51.360 [NOTICE] Document root is not set: start in Interop Mode
33374 segmentation fault  ./http_server -s 127.0.0.1:8443

[curl http3 document](https://github.com/curl/curl/blob/master/docs/HTTP3.md)

**Comment by dtikhonov** [comment] 2019-12-05 13:23
I reproduced it.  The problem is indeed in the driver: it expects there to be `-c` options.  Fix is coming.

In the meantime, use `-c` option.  The server won't do anything useful without it, anyway.

**Comment by litespeedtech** [comment] 2019-12-05 13:54
Fixed in release 2.7.1.

**Closed by litespeedtech** 2019-12-05 13:54 UTC
