### ISSUE TITLE
LSENG_SERVER assert failed in maybe_close_conn if client send new stream after server sent goaway

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#220] opened 2021-01-22 02:28 UTC
SMBF_CRYPTO only be set with handshake stream, and SMBF_HEADERS only be set with LSENG_HTTP_SERVER, so if client send new stream after server sent goaway, maybe_close_conn will assert failed and cause PROG exit!

![image](https://user-images.githubusercontent.com/12257285/105437608-55dafa80-5c9c-11eb-92a6-e2e295520873.png)

**Comment by dtikhonov** [comment] 2021-01-22 04:16
Is this something that you've seen happen or just an observation from reading the code?

**Comment by wangfuyu** [comment] 2021-01-22 07:38
> Is this something that you've seen happen or just an observation from reading the code?

This is happen on my program and I have check related code.

1) Run a LSENG_SERVER;
2) client send multi stream to server continuously;
3) server send goaway after sending response the 1st stream.

**Comment by dtikhonov** [comment] 2021-01-22 14:27
Oh I see what's going on -- I should have read your original comment more carefully!

**Comment by dtikhonov** [comment] 2021-01-25 15:47
> 2. client send multi stream to server continuously; (GQUIC)

This is a bit of an unexpected use case...  Please see whether proposed fix on branch `202101251044-fix-bug-220` works for you, @wangfuyu

**Comment by wangfuyu** [comment] 2021-01-26 13:45
> > 1. client send multi stream to server continuously; (GQUIC)
> 
> This is a bit of an unexpected use case... Please see whether proposed fix on branch `202101251044-fix-bug-220` works for you, @wangfuyu

![image](https://user-images.githubusercontent.com/12257285/105852745-ccbb1f00-601f-11eb-9e7c-5d9416f6b0d2.png)

**Comment by dtikhonov** [comment] 2021-01-26 13:58
1. Thanks for catching that and thanks for the review!
2. Yes, but _Google_ QUIC was designed to carry HTTP specifically; the library allows it because it can (and because we wanted to implement some non-HTTP demo apps).  IETF QUIC is different matter: it is a general-purpose transport protocol.

**Comment by litespeedtech** [comment] 2021-01-27 15:42
Fixed in 2.27.6 -- closing.

**Closed by litespeedtech** 2021-01-27 15:42 UTC
Labels: bug
