### ISSUE TITLE
BUG: dirty data

### ISSUE THREAD

**Issue by cang-mang** [litespeedtech/lsquic#112] opened 2020-03-03 04:09 UTC
In file lsquic_packet_out.c
In function split_largest_frame
To the end of this function, we have:

`const unsigned short adj = max_srec->sr_len - (unsigned short) len;`
`max_srec->sr_len = len;`
`for (n = max_idx + 1; n < n_srecs; ++n)`
`    srecs[n]->sr_off -= adj;`
`packet_out->po_data_sz -= adj;`
`return 0;`

But, before this code block, I think we must insert this line:
`memmove(packet_out->po_data + max_srec->sr_off + len, packet_out->po_data + max_srec->sr_off + max_srec->sr_len, packet_out->po_data_sz - max_srec->sr_off - max_srec->sr_len);`

Because the size of current frame in current packet is changed.

**Comment by dtikhonov** [comment] 2020-03-03 14:45
Thank you for the report.

The code works correctly.  It is tested by `test_bad_packbits_guess_3()` in _test/unittests/test_stream.c_.  You can run it in the debugger and see how it works.

The function does the following:
- [parse given STREAM frame](https://github.com/litespeedtech/lsquic/blob/v2.12.0/src/liblsquic/lsquic_packet_out.c#L497L507)
- [write the second half of the STREAM data to the new packet](https://github.com/litespeedtech/lsquic/blob/v2.12.0/src/liblsquic/lsquic_packet_out.c#L513L548)
- [overwrite the original STREAM frame inside the original packet with the first half of the STREAM data](https://github.com/litespeedtech/lsquic/blob/v2.12.0/src/liblsquic/lsquic_packet_out.c#L550L571)
- [adjust STREAM frame offsets of frames that follow the modified frame in the original packet and adjust original packet size](https://github.com/litespeedtech/lsquic/blob/v2.12.0/src/liblsquic/lsquic_packet_out.c#L573L577)

**Comment by litespeedtech** [comment] 2020-03-03 14:47
Closing -- not a bug.

**Closed by litespeedtech** 2020-03-03 14:47 UTC
