### ISSUE TITLE
Maybe a bug: forget to check lost-queue.

### ISSUE THREAD

**Issue by cang-mang** [litespeedtech/lsquic#136] opened 2020-06-29 02:46 UTC
In file lsquic_send_ctl.c
In function have_unacked_handshake_packets
It only checks `sc_unacked_packets` queue.
But I think, the `sc_lost_packets` queue should also be checked.

**Comment by dtikhonov** [comment] 2020-06-30 12:10
The logic is correct.  If a handshake packet is in the Lost queue, it means that a different retransmission mode should be selected in `get_retx_mode()`.

**Comment by litespeedtech** [comment] 2020-07-08 12:42
Not a bug -- closing.

**Closed by litespeedtech** 2020-07-08 12:42 UTC
