### ISSUE TITLE
Why not close connection immediately while CONNECTION_CLOSE frame in

### ISSUE THREAD

**Issue by wangfuyu** [litespeedtech/lsquic#281] opened 2021-05-26 15:01 UTC
Lsquic can not close connection immediately when CONNECTION_CLOSE frame in and cwnd used up.

Notes: 1) GQUIC full connection; 2) lsquic 2.27.3

![image](https://user-images.githubusercontent.com/12257285/119683184-06891e80-be76-11eb-8928-9993d3cd7296.png)

![image](https://user-images.githubusercontent.com/12257285/119683429-389a8080-be76-11eb-9026-400815fc9d6f.png)

![image](https://user-images.githubusercontent.com/12257285/119683468-418b5200-be76-11eb-9c60-568736448c6b.png)

**Comment by wangfuyu** [comment] 2021-05-26 15:14
I have got a case: Full connection received CONNECTION_CLOSE from client, but it would not be close and retransmit some lost pkts until idle timeout.

**Comment by wangfuyu** [comment] 2021-05-26 15:16
> I have got a case: Full connection received CONNECTION_CLOSE from client, but it would not be close and retransmit some lost pkts until idle timeout.

I think this is not a reasonable logic.

**Comment by wangfuyu** [comment] 2021-05-27 04:18
![Uploading image.png…]()

**Comment by wangfuyu** [comment] 2021-05-27 10:06
IETF QUIC ietf_full_conn_ci_tick processing is different with GQUIC:
![image](https://user-images.githubusercontent.com/12257285/119807876-25d78880-bf16-11eb-96fd-211d757f2b9e.png)

**Comment by litespeedtech** [comment] 2021-05-27 15:50
You are right, there are separate implementation of gQUIC and IEFT QUIC. 
gQUIC code may need to be updated to match the IEFT QUIC code, have FC_TICK_CLOSE set regardless. like you suggested. 
Can you please test if that change works as intended, make the connection close quickly?

**Comment by wangfuyu** [comment] 2021-05-28 06:59
> You are right, there are separate implementation of gQUIC and IEFT QUIC.
> gQUIC code may need to be updated to match the IEFT QUIC code, have FC_TICK_CLOSE set regardless. like you suggested.
> Can you please test if that change works as intended, make the connection close quickly?

If only set conn->ifc_flags with FC_TICK_CLOSE, connection can't be closed timely.  We must set tick |= TICK_CLOSE, and here IQUIC may have the same problem.

1) As I have mentioned above, RETURN_IF_OUT_OF_PACKETS will goto end logic when cwnd be used up. 
2) FC_TICK_CLOSE only be used in func immediate_close, but immediate_close only be called when if (conn->fc_flags & FC_IMMEDIATE_CLOSE_FLAGS).
3) But FC_IMMEDIATE_CLOSE_FLAGS not include FC_TICK_CLOSE.

**Comment by wangfuyu** [comment] 2021-05-28 08:16
> > You are right, there are separate implementation of gQUIC and IEFT QUIC.
> > gQUIC code may need to be updated to match the IEFT QUIC code, have FC_TICK_CLOSE set regardless. like you suggested.
> > Can you please test if that change works as intended, make the connection close quickly?
> 
> If only set conn->ifc_flags with FC_TICK_CLOSE, connection can't be closed timely. We must set tick |= TICK_CLOSE, and here IQUIC may have the same problem.
> 
> 1. As I have mentioned above, RETURN_IF_OUT_OF_PACKETS will goto end logic when cwnd be used up.
> 2. FC_TICK_CLOSE only be used in func immediate_close, but immediate_close only be called when (conn->fc_flags & FC_IMMEDIATE_CLOSE_FLAGS) == TRUE.
> 3. But FC_IMMEDIATE_CLOSE_FLAGS not include FC_TICK_CLOSE.

I think we can do as following:
![image](https://user-images.githubusercontent.com/12257285/119952707-e2415500-bfcf-11eb-97cb-6de219fd6362.png)

**Comment by wangfuyu** [comment] 2021-05-28 09:40
> > > You are right, there are separate implementation of gQUIC and IEFT QUIC.
> > > gQUIC code may need to be updated to match the IEFT QUIC code, have FC_TICK_CLOSE set regardless. like you suggested.
> > > Can you please test if that change works as intended, make the connection close quickly?
> > 
> > 
> > If only set conn->ifc_flags with FC_TICK_CLOSE, connection can't be closed timely. We must set tick |= TICK_CLOSE, and here IQUIC may have the same problem.
> > 
> > 1. As I have mentioned above, RETURN_IF_OUT_OF_PACKETS will goto end logic when cwnd be used up.
> > 2. FC_TICK_CLOSE only be used in func immediate_close, but immediate_close only be called when (conn->fc_flags & FC_IMMEDIATE_CLOSE_FLAGS) == TRUE.
> > 3. But FC_IMMEDIATE_CLOSE_FLAGS not include FC_TICK_CLOSE.
> 
> I think we can do some change, like:
> ![image](https://user-images.githubusercontent.com/12257285/119952707-e2415500-bfcf-11eb-97cb-6de219fd6362.png)

I found another problem: If have_delayed_packets, then full conn can not be close timely even CONNECTION_CLOSE frame in.

I think here should be changed:
![image](https://user-images.githubusercontent.com/12257285/119964315-aca26900-bfdb-11eb-859f-341b3b9b149c.png)

**Comment by wangfuyu** [comment] 2021-05-28 13:22
I have commit a PR: https://github.com/litespeedtech/lsquic/pull/284

**Comment by litespeedtech** [comment] 2021-05-28 13:24
I think the logic is getting too complicated. :-) 
If FC_RECV_CLOSE flag should trigger a immediate TICK_CLOSE regardless there are pending packets to send or not, generating a CONNECTION_CLOSE frame is optional, no exception case, then just code that way without that many branches. 

The question is: Is that always true?

**Comment by wangfuyu** [comment] 2021-05-28 13:37
> I think the logic is getting too complicated. :-)
> If FC_RECV_CLOSE flag should trigger a immediate TICK_CLOSE regardless there are pending packets to send or not, generating a CONNECTION_CLOSE frame is optional, no exception case, then just code that way without that many branches.
> 
> The question is: Is that always true?

No, after CONNECTION_CLOSE frame in, we may need send a CONNECTION_CLOSE to peer(This is what I have see from lsquic comments).

**Comment by litespeedtech** [comment] 2021-05-28 14:23
RFC9000 10.2 is about this.

> 10.2.2. Draining Connection State
> The draining state is entered once an endpoint receives a CONNECTION_CLOSE frame, which indicates that its peer is closing or draining. While otherwise identical to the closing state, an endpoint in the draining state MUST NOT send any packets. Retaining packet protection keys is unnecessary once a connection is in the draining state.
> 
> An endpoint that receives a CONNECTION_CLOSE frame MAY send a single packet containing a CONNECTION_CLOSE frame before entering the draining state, using a NO_ERROR code if appropriate. An endpoint MUST NOT send further packets. Doing so could result in a constant exchange of CONNECTION_CLOSE frames until one of the endpoints exits the closing state.
> 
> An endpoint MAY enter the draining state from the closing state if it receives a CONNECTION_CLOSE frame, which indicates that the peer is also closing or draining. In this case, the draining state ends when the closing state would have ended. In other words, the endpoint uses the same end time but ceases transmission of any packets on this connection.

I think the correct logic is to discard all pending packets, send one best effort CONNECTION_CLOSE frame, no retransmit.

**Comment by wangfuyu** [comment] 2021-05-28 14:49
> The closing and draining connection states exist to ensure that connections close cleanly and that delayed or reordered packets are properly discarded. These states SHOULD persist for at least three times the current PTO interval as defined in [QUIC-RECOVERY].

Do we need to persist for at least 3PTO?

**Comment by wangfuyu** [comment] 2021-05-28 14:53
> RFC9000 10.2 is about this.
> 
> > 10.2.2. Draining Connection State
> > The draining state is entered once an endpoint receives a CONNECTION_CLOSE frame, which indicates that its peer is closing or draining. While otherwise identical to the closing state, an endpoint in the draining state MUST NOT send any packets. Retaining packet protection keys is unnecessary once a connection is in the draining state.
> > An endpoint that receives a CONNECTION_CLOSE frame MAY send a single packet containing a CONNECTION_CLOSE frame before entering the draining state, using a NO_ERROR code if appropriate. An endpoint MUST NOT send further packets. Doing so could result in a constant exchange of CONNECTION_CLOSE frames until one of the endpoints exits the closing state.
> > An endpoint MAY enter the draining state from the closing state if it receives a CONNECTION_CLOSE frame, which indicates that the peer is also closing or draining. In this case, the draining state ends when the closing state would have ended. In other words, the endpoint uses the same end time but ceases transmission of any packets on this connection.
> 
> I think the correct logic is to discard all pending packets, send one best effort CONNECTION_CLOSE frame, no retransmit.

I agree this!

**Comment by litespeedtech** [comment] 2021-05-28 15:06
> Do we need to persist draining connection states for at least 3PTO?

Absolutely. :-)

**Comment by wangfuyu** [comment] 2021-05-31 03:56
@litespeedtech  I have simplified TICK_CLOSE, please check!

PR LINK:  https://github.com/litespeedtech/lsquic/pull/284

**Comment by litespeedtech** [comment] 2021-05-31 16:02
I merged the pull request. 
But there is a questionable change 
```
        tick |= TICK_SEND;
-       goto end;
+       goto end_write;
    }
```
This can be done when `IFC_CLOSING` or `FC_CLOSING` flag is set, but it may have side effect when connection should not be closed. Agree? 
I will add some extra logic to take care of it in next release.

**Comment by wangfuyu** [comment] 2021-06-01 02:11
> I found another problem: If have_delayed_packets and lsquic_send_ctl_can_send TRUE, then full conn can not be close timely even CONNECTION_CLOSE frame in.
> 
> Because if (have_delayed_packets) will goto end but not goto end_write.
> 
> I think here should be changed:
> ![image](https://user-images.githubusercontent.com/12257285/119964315-aca26900-bfdb-11eb-859f-341b3b9b149c.png)



> I merged the pull request.
> But there is a questionable change
> 
> ```
>         tick |= TICK_SEND;
> -       goto end;
> +       goto end_write;
>     }
> ```
> 
> This can be done when `IFC_CLOSING` or `FC_CLOSING` flag is set, but it may have side effect when connection should not be closed. Agree?
> I will add some extra logic to take care of it in next release.

As I have mentioned above: "If have_delayed_packets and lsquic_send_ctl_can_send TRUE, then full conn can not be close timely even CONNECTION_CLOSE frame in."

Could you tell me what is the specific meaning of "side effect"? Thanks!

**Comment by litespeedtech** [comment] 2021-06-01 02:28
The the side effect is, for a connection is not being closed, which is the most common state of a connection, when there is delayed packets, it should not attempt to send more, it is a waste of time, that's original intention of this logic. 
The change makes a connection close faster, but make handling more common case slower.

**Comment by wangfuyu** [comment] 2021-06-01 02:39
> The the side effect is, for a connection is not being closed, which is the most common state of a connection, when there is delayed packets, it should not attempt to send more, it is a waste of time, that's original intention of this logic.
> The change makes a connection close faster, but make handling more common case slower.

Maybe we can add CONNECTION_CLOSE check in the end logic? But I think it is too complicated.

![image](https://user-images.githubusercontent.com/12257285/120258933-86bfe180-c2c5-11eb-86d2-f61ffcf852ad.png)

**Comment by litespeedtech** [comment] 2021-06-01 02:54
That adds an extra branching in the common code path. 
My fix is
```
        if (conn->fc_flags & FC_CLOSING)
            goto end_write;
        else
            goto end;
```

**Comment by litespeedtech** [comment] 2021-06-09 13:15
The code change adds the side effect that CONNECTION_CLOSE frame was not delivered when initiate a connection close. :-)
I think we need to limit the behavior change to the case that a CONNECTION_CLOSE frame has been received, and make sure to send a CONNETION_CLOSE frame when initiate a connection close.

**Comment by wangfuyu** [comment] 2021-06-10 02:49
> > The the side effect is, for a connection is not being closed, which is the most common state of a connection, when there is delayed packets, it should not attempt to send more, it is a waste of time, that's original intention of this logic.
> > The change makes a connection close faster, but make handling more common case slower.
> 
> Maybe we can add CONNECTION_CLOSE check in the end logic? But I think it is too complicated.
> 
> ![image](https://user-images.githubusercontent.com/12257285/120258933-86bfe180-c2c5-11eb-86d2-f61ffcf852ad.png)



> The code change adds the side effect that CONNECTION_CLOSE frame was not delivered when initiate a connection close. :-)
> I think we need to limit the behavior change to the case that a CONNECTION_CLOSE frame has been received, and make sure to send a CONNETION_CLOSE frame when initiate a connection close.

Maybe we can do following: 
1) Execute RETURN_IF_OUT_OF_PACKETS before conn->ifc_flags = IFC_TICK_CLOSE;
2) Add CONNECTION_CLOSE check in the 'end' logic
 ![image](https://user-images.githubusercontent.com/12257285/120258933-86bfe180-c2c5-11eb-86d2-f61ffcf852ad.png)

**Comment by litespeedtech** [comment] 2021-06-10 03:28
It is a common code path, would rather avoid that. 
Extra checking should be added to the section handling connection close only.

**Comment by litespeedtech** [comment] 2021-06-12 02:29
Please check commit (https://github.com/litespeedtech/lsquic/commit/47440e4eaf376676ac658a2b7cfb9470f350e385) .

**Comment by litespeedtech** [comment] 2021-06-15 22:20
No comment == No problem. issue closed, again. :-)

**Closed by litespeedtech** 2021-06-15 22:20 UTC
