### ISSUE TITLE
lsquic support use in iOS?

### ISSUE THREAD

**Issue by lsj9383** [litespeedtech/lsquic#242] opened 2021-03-14 17:11 UTC
I am looking for a quic library that can be used in ios.

And I am concerned that lsquic supports MacOS, so I am confused whether it also supports iOS, I still don’t know enough about the difference between MacOS and iOS.

Thanks your help.

**Comment by dtikhonov** [comment] 2021-03-16 13:40
> I still don’t know enough about the difference between MacOS and iOS.

Neither do we: we are a Linux shop.  If someone would make a PR for iOS support, we'd consider it.

This is a duplicate of bug #3.

**Closed** 2021-03-17 12:12 UTC
